-- ============================================================================
-- EstimateIQ – Initiales Supabase-Schema (Postgres + pgvector)
-- ============================================================================
-- Ausführen im Supabase SQL Editor (Dashboard → SQL Editor → New query)
-- oder via psql gegen die DATABASE_URL.
--
-- Das Backend verbindet sich direkt per Connection String (postgres-Rolle)
-- und filtert JEDE Query auf tenant_id. RLS ist zusätzlich als Deny-All
-- aktiviert, damit die Tabellen NICHT über die PostgREST-API (anon-key)
-- lesbar sind – der anon-key steckt im Frontend-Bundle.
-- ============================================================================

create extension if not exists vector;

-- ── Tenants ──────────────────────────────────────────────────────────────────

create table if not exists tenants (
    id          text primary key default gen_random_uuid()::text,
    name        text not null,
    erstellt_am timestamptz not null default now()
);

-- Zuordnung Supabase-Auth-User → Tenant.
-- user_id = auth.users.id (UUID als Text; bewusst ohne FK auf das auth-Schema).
-- Teamrollen & Permissions (RBAC) – siehe Migration 003 für Details/Upgrade-Pfad.
create table if not exists teamrollen (
    id           bigint generated by default as identity primary key,
    tenant_id    text not null references tenants(id) on delete cascade,
    name         varchar(100) not null,
    is_system    boolean not null default false,
    beschreibung text,
    erstellt_am  timestamptz not null default now(),
    constraint uq_teamrollen_tenant_name unique (tenant_id, name)
);
create index if not exists ix_teamrollen_tenant on teamrollen(tenant_id);

create table if not exists permissions (
    key          text primary key,
    bereich      varchar(50) not null,
    beschreibung text not null
);

create table if not exists teamrolle_permissions (
    teamrolle_id   bigint not null references teamrollen(id) on delete cascade,
    permission_key text not null references permissions(key) on delete cascade,
    primary key (teamrolle_id, permission_key)
);

create table if not exists audit_log (
    id             bigint generated by default as identity primary key,
    tenant_id      text not null references tenants(id) on delete cascade,
    actor_user_id  text not null,
    aktion         varchar(100) not null,
    ziel_typ       varchar(50) not null,
    ziel_id        varchar(100) not null,
    vorher         jsonb,
    nachher        jsonb,
    erstellt_am    timestamptz not null default now()
);
create index if not exists ix_audit_log_tenant on audit_log(tenant_id);

create table if not exists tenant_users (
    user_id      text primary key,
    tenant_id    text not null references tenants(id) on delete cascade,
    email        text,
    teamrolle_id bigint not null references teamrollen(id),
    status       text not null default 'aktiv',   -- 'aktiv' | 'eingeladen'
    rolle        text not null default 'mitglied' -- LEGACY, nirgends mehr gelesen
);
create index if not exists ix_tenant_users_tenant on tenant_users(tenant_id);

-- ── Rollen & Stundensätze ────────────────────────────────────────────────────

create table if not exists rollen (
    id              bigint generated by default as identity primary key,
    tenant_id       text not null references tenants(id) on delete cascade,
    name            varchar(100) not null,
    stundensatz_eur double precision not null,
    gueltig_ab      timestamptz not null default now(),
    erstellt_am     timestamptz not null default now(),
    constraint uq_rollen_tenant_name unique (tenant_id, name)
);
create index if not exists ix_rollen_tenant on rollen(tenant_id);

-- ── Projekte ─────────────────────────────────────────────────────────────────

create table if not exists projekte (
    id              bigint generated by default as identity primary key,
    tenant_id       text not null references tenants(id) on delete cascade,
    name            varchar(200) not null,
    beschreibung    text not null default '',
    kunde           varchar(200) not null default '',
    status          varchar(50) not null default 'entwurf',
    ist_referenz    boolean not null default false,
    ersteller_id    text,          -- Supabase user_id; NULL = firmenweit / kein Owner
    embedding       vector(384),
    ablehnungsgrund text,
    leitung         varchar(200),
    auftragswert    double precision,
    abrechnung_typ  varchar(50),
    laufzeit_start  varchar(20),
    laufzeit_end    varchar(20),
    erstellt_am     timestamptz not null default now()
);
create index if not exists ix_projekte_tenant on projekte(tenant_id);
create index if not exists ix_projekte_ersteller on projekte(ersteller_id);

-- ── Leistungspositionen ──────────────────────────────────────────────────────

create table if not exists leistungspositionen (
    id                   bigint generated by default as identity primary key,
    tenant_id            text not null references tenants(id) on delete cascade,
    projekt_id           bigint not null references projekte(id) on delete cascade,
    rolle_id             bigint references rollen(id) on delete set null,
    beschreibung_text    text not null,
    soll_stunden         double precision not null,
    ist_stunden          double precision,
    stundensatz_snapshot double precision,
    phase                varchar(100),
    embedding            vector(384),
    ist_historisch       boolean not null default false,
    erstellt_am          timestamptz not null default now()
);
create index if not exists ix_positionen_tenant  on leistungspositionen(tenant_id);
create index if not exists ix_positionen_projekt on leistungspositionen(projekt_id);

-- ── Angebote ─────────────────────────────────────────────────────────────────

create table if not exists angebote (
    id           bigint generated by default as identity primary key,
    tenant_id    text not null references tenants(id) on delete cascade,
    projekt_id   bigint not null references projekte(id) on delete cascade,
    titel        varchar(200) not null default '',
    status       varchar(50) not null default 'entwurf',
    pdf_pfad     varchar(500),
    versendet_am timestamptz,
    erstellt_am  timestamptz not null default now()
);
create index if not exists ix_angebote_tenant on angebote(tenant_id);

-- ── Vektor-Indizes (Cosine, HNSW) ────────────────────────────────────────────

create index if not exists ix_positionen_embedding
    on leistungspositionen using hnsw (embedding vector_cosine_ops);

create index if not exists ix_projekte_embedding
    on projekte using hnsw (embedding vector_cosine_ops);

-- ── Row Level Security: Deny-All ─────────────────────────────────────────────
-- RLS ohne Policies = kein Zugriff für anon/authenticated über PostgREST.
-- Das Backend (postgres-Rolle über Connection String) ist davon nicht betroffen.

alter table tenants             enable row level security;
alter table tenant_users        enable row level security;
alter table rollen              enable row level security;
alter table projekte            enable row level security;
alter table leistungspositionen enable row level security;
alter table angebote            enable row level security;
alter table teamrollen          enable row level security;
alter table permissions         enable row level security;
alter table teamrolle_permissions enable row level security;
alter table audit_log           enable row level security;

-- ============================================================================
-- Nächste Schritte:
--   tenant_users.teamrolle_id ist NOT NULL – ein Tenant braucht erst die
--   Systemrollen (Owner/Admin/Mitarbeiter/Nur-Lesen), bevor ihm ein Benutzer
--   zugeordnet werden kann. NICHT mehr per Hand-SQL anlegen, sondern:
--
--     python -m estimateiq.angebot.seed
--
--   Das legt Tenant + Systemrollen (via ensure_systemrollen) + Demo-Login-User
--   in einem Schritt an. Für einen eigenen Tenant ohne Demo-Daten: seed.py als
--   Vorlage nehmen oder ensure_systemrollen(db, tenant_id) direkt aufrufen.
-- ============================================================================
