-- ============================================================================
-- EstimateIQ – Migration 003: Teamrollen & Permissions (RBAC Phase 1)
-- ============================================================================
-- Auf bestehende Supabase-Datenbanken anwenden (SQL Editor). NICHT idempotent
-- bei mehrfacher Ausführung mit Daten dazwischen – einmalig nach dem Deploy
-- des neuen Backend-Codes ausführen, dann ist das Schema synchron.
--
-- Reihenfolge wichtig: Tabellen → Katalog befüllen → Systemrollen je Tenant →
-- tenant_users befüllen (Backfill) → NOT NULL erzwingen (nur hier möglich,
-- SQLite kann das nicht nachträglich – siehe database.py-Kommentar).
-- ============================================================================

-- ── Neue Tabellen ─────────────────────────────────────────────────────────────

create table if not exists teamrollen (
    id           bigint generated by default as identity primary key,
    tenant_id    text not null references tenants(id) on delete cascade,
    name         varchar(100) not null,
    is_system    boolean not null default false,
    beschreibung text,
    erstellt_am  timestamptz not null default now(),
    constraint uq_teamrollen_tenant_name unique (tenant_id, name)
);
create index if not exists ix_teamrollen_tenant on teamrollen(tenant_id);

create table if not exists permissions (
    key          text primary key,
    bereich      varchar(50) not null,
    beschreibung text not null
);

create table if not exists teamrolle_permissions (
    teamrolle_id   bigint not null references teamrollen(id) on delete cascade,
    permission_key text not null references permissions(key) on delete cascade,
    primary key (teamrolle_id, permission_key)
);

create table if not exists audit_log (
    id             bigint generated by default as identity primary key,
    tenant_id      text not null references tenants(id) on delete cascade,
    actor_user_id  text not null,
    aktion         varchar(100) not null,
    ziel_typ       varchar(50) not null,
    ziel_id        varchar(100) not null,
    vorher         jsonb,
    nachher        jsonb,
    erstellt_am    timestamptz not null default now()
);
create index if not exists ix_audit_log_tenant on audit_log(tenant_id);

alter table teamrollen          enable row level security;
alter table permissions         enable row level security;
alter table teamrolle_permissions enable row level security;
alter table audit_log           enable row level security;

-- ── Permission-Katalog befüllen ──────────────────────────────────────────────
-- Muss synchron zu estimateiq/angebot/permissions.py::KATALOG gehalten werden.

insert into permissions (key, bereich, beschreibung) values
    ('dashboard.view',          'dashboard', 'Dashboard aufrufen'),
    ('projekte.erstellen',      'projekte',  'Neues Projekt/Angebot anlegen'),
    ('projekte.bearbeiten',     'projekte',  'Projekt bearbeiten (kombiniert mit Ownership)'),
    ('projekte.loeschen',       'projekte',  'Projekt löschen (kombiniert mit Ownership)'),
    ('projekte.status_aendern','projekte',  'Angebotsstatus ändern, Angebot/PDF erzeugen'),
    ('projekte.alle_ansehen',  'projekte',  'Alle Projekte im Tenant sehen (nicht nur eigene)'),
    ('projekte.marge_einsehen','projekte',  'Interne Kosten/Marge/Stundensätze einsehen'),
    ('positionen.bearbeiten',  'positionen','Leistungspositionen anlegen/ändern/löschen'),
    ('rollen.verwalten',       'rollen',    'Stundensatz-Rollen verwalten'),
    ('import.durchfuehren',    'import',    'CSV/Excel-Import durchführen'),
    ('settings.manage_users',  'settings',  'Team & Rollen verwalten'),
    ('settings.manage_layout', 'settings',  'Dashboard-Layout verwalten (Phase 2, noch ungenutzt)'),
    ('settings.manage_kpis',   'settings',  'Eigene Kennzahlen verwalten (Phase 3, noch ungenutzt)')
on conflict (key) do nothing;

-- ── Systemrollen je bestehendem Tenant anlegen ───────────────────────────────
-- Owner/Admin bekommen ALLE Permissions, Mitarbeiter/Nur-Lesen eine Teilmenge
-- (siehe estimateiq/angebot/permissions.py::SYSTEMROLLEN – hier synchron
-- gehalten). do-Block, weil pro Tenant iteriert werden muss.

do $$
declare
    t record;
    r_owner bigint; r_admin bigint; r_mitarbeiter bigint; r_nurlesen bigint;
begin
    for t in select id from tenants loop
        insert into teamrollen (tenant_id, name, is_system)
            values (t.id, 'Owner', true)
            on conflict (tenant_id, name) do nothing;
        insert into teamrollen (tenant_id, name, is_system)
            values (t.id, 'Admin', true)
            on conflict (tenant_id, name) do nothing;
        insert into teamrollen (tenant_id, name, is_system)
            values (t.id, 'Mitarbeiter', true)
            on conflict (tenant_id, name) do nothing;
        insert into teamrollen (tenant_id, name, is_system)
            values (t.id, 'Nur-Lesen', true)
            on conflict (tenant_id, name) do nothing;

        select id into r_owner       from teamrollen where tenant_id = t.id and name = 'Owner';
        select id into r_admin       from teamrollen where tenant_id = t.id and name = 'Admin';
        select id into r_mitarbeiter from teamrollen where tenant_id = t.id and name = 'Mitarbeiter';
        select id into r_nurlesen    from teamrollen where tenant_id = t.id and name = 'Nur-Lesen';

        -- Owner + Admin: alle Permissions
        insert into teamrolle_permissions (teamrolle_id, permission_key)
            select r_owner, key from permissions
            on conflict do nothing;
        insert into teamrolle_permissions (teamrolle_id, permission_key)
            select r_admin, key from permissions
            on conflict do nothing;

        -- Mitarbeiter
        insert into teamrolle_permissions (teamrolle_id, permission_key)
            select r_mitarbeiter, key from unnest(array[
                'dashboard.view','projekte.erstellen','projekte.bearbeiten',
                'projekte.loeschen','projekte.status_aendern',
                'positionen.bearbeiten','import.durchfuehren'
            ]) as key
            on conflict do nothing;

        -- Nur-Lesen
        insert into teamrolle_permissions (teamrolle_id, permission_key)
            select r_nurlesen, key from unnest(array[
                'dashboard.view','projekte.alle_ansehen','projekte.marge_einsehen'
            ]) as key
            on conflict do nothing;
    end loop;
end $$;

-- ── tenant_users erweitern + befüllen ────────────────────────────────────────

alter table tenant_users add column if not exists teamrolle_id bigint references teamrollen(id);
alter table tenant_users add column if not exists status text not null default 'aktiv';

-- Backfill: rolle='admin' → Owner, rolle='mitglied' → Mitarbeiter, je Tenant.
update tenant_users tu
set teamrolle_id = tr.id
from teamrollen tr
where tu.teamrolle_id is null
  and tr.tenant_id = tu.tenant_id
  and tr.name = case when tu.rolle = 'admin' then 'Owner' else 'Mitarbeiter' end;

-- Erst jetzt, nach dem Backfill, die Constraint erzwingen (Postgres kann das,
-- SQLite nicht – deshalb ist die Spalte dort dauerhaft nullable, siehe
-- estimateiq/angebot/database.py).
alter table tenant_users alter column teamrolle_id set not null;

-- Die alte rolle-Spalte bleibt physisch bestehen, wird ab sofort nirgends
-- mehr gelesen. Wird in Migration 004 gedroppt (bewusst getrennter Schritt).

-- ============================================================================
-- Danach prüfen:
--   select tu.email, tr.name as teamrolle from tenant_users tu
--     join teamrollen tr on tr.id = tu.teamrolle_id;
-- ============================================================================
