-- ============================================================================
-- EstimateIQ – Migration 004: KPI-Definitionen & Dashboard-Layout (Phase 2/3)
-- ============================================================================
-- Auf bestehende Supabase-Datenbanken anwenden (SQL Editor). Idempotent
-- (create table if not exists, on conflict do nothing).
--
-- kpi_definitions: System-KPIs (fest programmierter Resolver, siehe
--   estimateiq/angebot/kpi_registry.py::SYSTEM_KPI_RESOLVER) UND Custom-KPIs
--   (generischer Builder: quelle/feld/aggregation/filters, serverseitig
--   gegen kpi_registry.py::REGISTRY validiert – kein freies SQL).
-- dashboard_layouts: scope_ref_id ist NIE NULL (Sentinel '' für
--   'tenant_default'), da NULL in einem Unique-Constraint auf Postgres nicht
--   als Duplikat gilt und die Eindeutigkeit sonst nicht griffe.
-- ============================================================================

create table if not exists kpi_definitions (
    id                  bigint generated by default as identity primary key,
    tenant_id           text not null references tenants(id) on delete cascade,
    key                 varchar(100) not null,
    label               varchar(200) not null,
    beschreibung        text,
    is_system           boolean not null default false,
    quelle              varchar(50),
    feld                varchar(100),
    aggregation         varchar(20),
    filters_json        text,
    zeitraum_json       text,
    darstellungstyp     varchar(20) not null default 'zahl',
    format              varchar(20),
    required_permission varchar(100),
    created_by          text,
    erstellt_am         timestamptz not null default now(),
    constraint uq_kpi_definitions_tenant_key unique (tenant_id, key)
);
create index if not exists ix_kpi_definitions_tenant on kpi_definitions(tenant_id);

create table if not exists dashboard_layouts (
    id            bigint generated by default as identity primary key,
    tenant_id     text not null references tenants(id) on delete cascade,
    scope         varchar(20) not null,           -- 'tenant_default' | 'role' | 'user'
    scope_ref_id  text not null default '',
    layout_json   text not null,
    updated_by    text not null,
    updated_at    timestamptz not null default now(),
    constraint uq_dashboard_layouts_scope unique (tenant_id, scope, scope_ref_id)
);
create index if not exists ix_dashboard_layouts_tenant on dashboard_layouts(tenant_id);

alter table kpi_definitions   enable row level security;
alter table dashboard_layouts enable row level security;

-- ── System-KPIs je bestehendem Tenant anlegen ────────────────────────────────
-- Muss synchron zu estimateiq/angebot/kpi_registry.py::SYSTEM_KPI_KATALOG
-- gehalten werden.

insert into kpi_definitions (tenant_id, key, label, is_system, darstellungstyp, format, required_permission)
select t.id, v.key, v.label, true, v.darstellungstyp, v.format, v.required_permission
from tenants t
cross join (values
    ('offene_angebote_anzahl',    'Offene Angebote',           'zahl',    'anzahl',  null),
    ('offene_angebote_wert',      'Offene Angebote (Wert)',     'zahl',    'eur',     'projekte.marge_einsehen'),
    ('trefferquote',              'Trefferquote',                'zahl',    'prozent', null),
    ('laufende_projekte_tabelle', 'Laufende Projekte',           'tabelle', null,      null)
) as v(key, label, darstellungstyp, format, required_permission)
on conflict (tenant_id, key) do nothing;

-- ============================================================================
-- Danach: python -m estimateiq.angebot.seed erzeugt neue Tenants automatisch
-- mit System-KPIs (ensure_system_kpis()); für Bestandstenants erledigt genau
-- dieses Skript hier die Nacherfassung.
-- ============================================================================
